language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - "sudo apt-get install -qq libhdf5-serial-dev"
install:
  - "pip install -r requirements_travis.txt"
script:
  - "flake8 allel"
  - "nosetests -v --with-doctest allel"
